### ISSUE TITLE
Fluid Pattern Terminal crashes when adding recipes from GTCE via JEI

### ISSUE THREAD

**Issue by TheEnderek0** [GlodBlock/AE2FluidCraft-Rework#135]
When adding recipes via JEI from GTCE this crash happens:
```
java.lang.NoSuchMethodError: gregtech.integration.jei.recipe.GTRecipeWrapper.isNotConsumedItem(I)Z
    at com.glodblock.github.integration.gregtech.GregUtil.isNotConsume(GregUtil.java:11)
    at com.glodblock.github.integration.jei.RecipeTransferBuilder.split(RecipeTransferBuilder.java:78)
    at com.glodblock.github.integration.jei.RecipeTransferBuilder.<init>(RecipeTransferBuilder.java:62)
    at com.glodblock.github.integration.jei.FluidPatternTerminalRecipeTransferHandler.transferRecipe(FluidPatternTerminalRecipeTransferHandler.java:45)
    at com.glodblock.github.integration.jei.FluidPatternTerminalRecipeTransferHandler.transferRecipe(FluidPatternTerminalRecipeTransferHandler.java:20)
    at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:47)
    at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:26)
    at mezz.jei.gui.recipes.RecipesGui.actionPerformed(RecipesGui.java:451)
    at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:443)
    at mezz.jei.gui.recipes.RecipesGui.mouseClicked(RecipesGui.java:336)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at mezz.jei.gui.recipes.RecipesGui.handleMouseInput(RecipesGui.java:304)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    ```

**Comment by GlodBlock** [comment]
fixed in https://github.com/AE2-UEL/AE2FluidCraft-Rework/releases/tag/2.5.4-r
