### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ElPudgino** [GlodBlock/AE2FluidCraft-Rework#181]
I have AE2UEL installed but it crashes and says it need applied energistics 2 installed
[15:57:15] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod ae2fc (AE2 Fluid Crafting) requires [appliedenergistics2@[v0.56.5,)]
[15:57:15] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod ae2fc (AE2 Fluid Crafting) requires [appliedenergistics2@[v0.56.5,)]
        at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by WaitingIdly** [comment]
that says it requires ae2 of a version of at least `0.56.5` - are you sure you have at least that version of ae2el installed?

**Comment by ElPudgino** [comment]
I had 0.56.6
