### ISSUE TITLE
Lost connection

### ISSUE THREAD

**Issue by Pilad** [GlodBlock/AE2FluidCraft-Rework#26]
Server Thermos / ae2fc-1.7.10-g07b03d1
When an encoded template is placed in a dual  interface is thrown from the server with this log
[21:44:55 WARN]: Failed to handle packet for /127.0.0.1:63944
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
        at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:187) ~[NetworkEventBus$EventMethod.class:?]
        at appeng.me.NetworkEventBus$EventMethod.access$400(NetworkEventBus.java:161) ~[NetworkEventBus$EventMethod.class:?]
        at appeng.me.NetworkEventBus$MENetworkEventInfo.invoke(NetworkEventBus.java:212) ~[NetworkEventBus$MENetworkEventInfo.class:?]
        at appeng.me.NetworkEventBus$MENetworkEventInfo.access$200(NetworkEventBus.java:198) ~[NetworkEventBus$MENetworkEventInfo.class:?]
        at appeng.me.NetworkEventBus.postEvent(NetworkEventBus.java:108) ~[NetworkEventBus.class:?]
        at appeng.me.Grid.postEvent(Grid.java:217) ~[Grid.class:?]
        at appeng.helpers.DualityInterface.updateCraftingList(DualityInterface.java:373) ~[DualityInterface.class:?]
        at appeng.helpers.DualityInterface.onChangeInventory(DualityInterface.java:179) ~[DualityInterface.class:?]
        at appeng.tile.inventory.AppEngInternalInventory.func_70299_a(AppEngInternalInventory.java:158) ~[AppEngInternalInventory.class:?]
        at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77) ~[aay.class:?]
        at appeng.container.slot.AppEngSlot.func_75215_d(AppEngSlot.java:108) ~[AppEngSlot.class:?]
        at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftInventoryView.setItem(CraftInventoryView.java:53) ~[CraftInventoryView.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.inventory.Container.func_75144_a(Container.java:290) ~[zs.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1997) ~[nh.class:?]
        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_331]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_331]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_331]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_331]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_331]
        at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:179) ~[NetworkEventBus$EventMethod.class:?]
        ... 22 more
Caused by: java.lang.NullPointerException
        at appeng.me.cache.CraftingGridCache.updatePatterns(CraftingGridCache.java:256) ~[CraftingGridCache.class:?]
        at appeng.me.cache.CraftingGridCache.updateCPUClusters(CraftingGridCache.java:328) ~[CraftingGridCache.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_331]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_331]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_331]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_331]
        at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:179) ~[NetworkEventBus$EventMethod.class:?]
        ... 22 more
[21:44:55 INFO]: Pilad lost connection: Internal server error
[21:44:55 INFO]: Pilad left the game.

**Comment by Pilad** [comment]
![изображение](https://user-images.githubusercontent.com/9840821/177817961-a28d47cb-63da-45bc-b6f9-02f03d4f2839.png)
This happens if the craft is liquid, if there are items at the entrance, then everything is fine.

**Comment by Pilad** [comment]
Work fine
![изображение](https://user-images.githubusercontent.com/9840821/177818213-7368bc28-df8f-4b9a-9a08-7fed34f23378.png)

**Comment by Pilad** [comment]
I think I tried to paste the encoded template that was from this version of the mod. Now again I made the template again and there is no error.
https://github.com/GlodBlock/AE2FluidCraft-Rework/pull/24
