### ISSUE TITLE
Crash durring startup: no class found for iron

### ISSUE THREAD

**Issue by Shibva** [GlodBlock/AE2FluidCraft-Rework#30]
```---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/25/22 12:31 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: iron
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: iron
	at com.glodblock.github.common.block.BlockFluidDiscretizer.<init>(BlockFluidDiscretizer.java:14)
	at com.glodblock.github.loader.ItemAndBlockHolder.<clinit>(ItemAndBlockHolder.java:10)
	at com.glodblock.github.FluidCraft.init(FluidCraft.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 977017920 bytes (931 MB) / 2147483648 bytes (2048 MB) up to 11240734720 bytes (10720 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10720m -Xms256m -XX:+UseG1GC -XX:ParallelGCThreads=4 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHI	CodeChickenCore{1.1.5} [CodeChicken Core] (minecraft.jar) 
	UCHI	NotEnoughItems{2.2.10-GTNH} [NotEnoughItems] (NotEnoughItems-1.7.10-2.2.10-GTNH.jar) 
	UCHI	ThE-core{1.0.0.1} [Thaumic Energistics Core] (minecraft.jar) 
	UCHI	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHI	FoamFixCore{1.0.0} [FoamFixCore] (minecraft.jar) 
	UCHI	WitcheryExtras_ASM{0.1-Beta} [WitcheryExtras_ASM] (minecraft.jar) 
	UCHI	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHI	ItemBlacklist{1.2.0.8} [ItemBlacklist] (ItemBlacklist-1.7.10-1.2.0.8.jar) 
	UCHI	adventurebackpack{1.0.4-GTNH} [Adventure Backpack] (adventurebackpack-1.7.10-1.0.4-GTNH.jar) 
	UCHI	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHE	ae2fc{g3ebf64f} [AE2 Fluid Crafting] (ae2fc-1.7.10-g3ebf64f.jar) 
	UCHI	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHI	ae2stuff{0.5.0.56} [AE2 Stuff] (ae2stuff-0.5.0.56-mc1.7.10.jar) 
	UCHI	aiimprovements{0.0.1.8} [AI Improvements] (AIImprovements-1.7.10-0.0.1b8.jar) 
	UCHI	AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.7.10-3.1.1.jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHI	Waila{1.5.20} [Waila] (Waila-1.7.10-1.5.20.jar) 
	UCHI	Automagy{0.28.2} [Automagy] (Automagy-1.7.10-0.28.2.jar) 
	UCHI	autooredictconv{1.7.10-1.3.1} [Auto Ore Dictionary Converter] (autooredictconv-1.7.10-1.3.1.jar) 
	UCHI	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHI	Avaritia{1.13} [Avaritia] (Avaritia-1.13.jar) 
	UCHI	wanionlib{1.7.10-1.8} [WanionLib] (WanionLib-1.7.10-1.8.jar) 
	UCHI	avaritiaddons{1.4b} [Avaritiaddons] (Avaritiaddons-1.4b.jar) 
	UCHI	battlegear2{1.7.10-1.1.1.8} [Mine & Blade Battlegear 2] (battlegear2-1.7.10-1.1.1.8.jar) 
	UCHI	baublesstuff{2.1.2} [Baubles Stuff] (baublesstuff-2.1.2.jar) 
	UCHI	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHI	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] (Forbidden Magic-1.7.10-0.575.jar) 
	UCHI	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHI	BloodArsenal{1.2-5} [Blood Arsenal] (BloodArsenal-1.7.10-1.2-5.jar) 
	UCHI	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHI	DragonAPI{v31b} [DragonAPI] (DragonAPI 1.7.10 V31b.jar) 
	UCHI	ChromatiCraft{v31b} [ChromatiCraft] (ChromatiCraft 1.7.10 V31b.jar) 
	UCHI	chunkpregenerator{2.5.0} [Chunk Pregenerator] (Chunk Pregenerator-V1.7.10-2.5.3.jar) 
	UCHI	MineTweaker3{3.1.0} [MineTweaker 3] (CraftTweaker-1.7.10-3.1.0-legacy.jar) 
	UCHI	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHI	draconicpatcher{1.0} [Draconic Patcher] (draconicpatcher-1.0.jar) 
	UCHI	dsurround{1.0.6.4} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.6.4.jar) 
	UCHI	extracells{2.4.0} [Extra Cells 2] (ExtraCells-1.7.10-2.4.0.jar) 
	UCHI	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHI	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.0.jar) 
	UCHI	forgeendertech{1.7.10-1.9.2.0} [Forge Endertech] (ForgeEndertech-1.7.10-1.9.2.0-build.0061.jar) 
	UCHI	hbm{1.0.27 BETA (4291)} [Hbm's Nuclear Tech] (HBM-NTM-.1.0.27_X4291.jar) 
	UCHI	InGameModConfigs{1.0.0.1} [InGame Mod Configs] (InGameModConfigs-1.7.10-1.0.0.1-client.jar) 
	UCHI	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHI	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHI	mdecore{v1.0-mc1.7.10} [MattDahEpic Core] (mdecore-1.0.jar) 
	UCHI	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.1.jar) 
	UCHI	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.7.10-1.9.jar) 
	UCHI	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UCHI	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHI	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-122.jar) 
	UCHI	Schematica{1.7.6.131} [Schematica] (Schematica-1.7.10-1.7.6.131-universal.jar) 
	UCHI	spongemixins{1.5.0} [SpongeMixins Loader] (SpongeMixins-1.5.0.jar) 
	UCHI	symcalc{0.14} [Symcalc] (symcalc-0.14.jar) 
	UCHI	TaintedMagic{8.1.1} [Tainted Magic] (Tainted-Magic-1.7.10-8.1.1.jar) 
	UCHI	tcinventoryscan{1.0.11} [TC Inventory Scanning] (tcinventoryscan-mc1.7.10-1.0.11.jar) 
	UCHI	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHI	tcneiadditions{1.1.1.0-pre} [Thaumcraft NEI Additions] (tcneiadditions-1.7.10-1.1.1.0-pre.jar) 
	UCHI	ThaumcraftMobAspects{1.0.0-GTNH} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.10-1.0.0-GTNH.jar) 
	UCHI	ThaumicExploration{GRADLETOKEN_VERSION} [Thaumic Exploration] (Thaumic-Exploration-1.7.10-1.1.85-GTNH.jar) 
	UCHI	thaumicenergistics{1.1.3.0} [Thaumic Energistics] (thaumicenergistics-1.1.3.0.jar) 
	UCHI	ThaumicHorizons{1.2.1.2} [ThaumicHorizons] (ThaumicHorizons-1.7.10-1.2.1.2.jar) 
	UCHI	thaumicsanity{1.0} [thaumicsanity] (thaumicSanity-1.0-1.7.10-9.jar) 
	UCHI	thetitans{indev-0.5} [The Titans Mod] (The Titans MC 1.7.10 version-0.5 beta v0712.jar) 
	UCHI	TitansAnimationAPI{1.2.4} [TitansAnimationAPI] (The Titans MC 1.7.10 version-0.5 beta v0712.jar) 
	UCHI	VillageNames{4.3.12} [§6Village Names] (VillageNames-1.7.10-4.3.12.jar) 
	UCHI	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCHI	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHI	WitcheryExtras{1.1.5} [Witchery++] (WitcheryExtras-1.7.10-1.1.5.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 516.59' Renderer: 'NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2'
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	List of loaded APIs: 
		* AgriCraftAPI (1.0) from DragonAPI 1.7.10 V31b.jar
		* AppleCoreAPI (3.1.0) from AppleCore-mc1.7.10-3.1.1.jar
		* appliedenergistics2|API (@aeversion@) from DragonAPI 1.7.10 V31b.jar
		* BattlePlayer (0.1) from battlegear2-1.7.10-1.1.1.8.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* BloodMagicAPI (1.3.3-13) from BloodMagic-1.7.10-1.3.3-17.jar
		* BotaniaAPI (61) from Avaritia-1.13.jar
		* CoFHAPI (1.7.10R1.0.2) from DragonAPI 1.7.10 V31b.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from HBM-NTM-.1.0.27_X4291.jar
		* DraconicEvolution|API (1.2) from Draconic-Evolution-1.7.10-1.0.2h.jar
		* DualWield (0.1) from battlegear2-1.7.10-1.1.1.8.jar
		* Guide-API|API (1.7.10-1.0.1-20) from Guide-API-1.7.10-1.0.1-20.jar
		* Heraldry (alpha) from battlegear2-1.7.10-1.1.1.8.jar
		* minechemAPI (1.7.10R1) from DragonAPI 1.7.10 V31b.jar
		* neresources|API (1.0) from NotEnoughResources-1.7.10-0.1.0-122.jar
		* Quiver (0.2) from battlegear2-1.7.10-1.1.1.8.jar
		* SchematicaAPI (1.1) from Schematica-1.7.10-1.7.6.131-universal.jar
		* SchematicaAPI|Events (1.1) from Schematica-1.7.10-1.7.6.131-universal.jar
		* Shield (0.1) from battlegear2-1.7.10-1.1.1.8.jar
		* Thaumcraft|API (4.2.2.0) from Thaumcraft-1.7.10-4.2.3.5.jar
		* thaumicenergistics|API (1.1) from thaumicenergistics-1.1.3.0.jar
		* WailaAPI (1.2) from Waila-1.7.10-1.5.20.jar
		* Weapons (0.1) from battlegear2-1.7.10-1.1.1.8.jar
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 516.59
	OpenGlRenderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8```

**Comment by GlodBlock** [comment]
i saw a very sus core mod in your list: `DragonAPI ASM`. i am not sure what reika did to the villian material since i can load it in other modpacks.
try this [ae2fc-1.7.10-g56d81ee.zip](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/9181907/ae2fc-1.7.10-g56d81ee.zip), don't forget to unzip it.

**Comment by Shibva** [comment]
This version instance that you provided me booted up successfully; it did crash once but this is common behavior for reikas mod chromaticraft (research handler); this crash usually only happens once there is a pack change and resolves itself after the second boot

this instance has fixed the issue and should know that the previous Version before the public update on curse was working as well


and just so you have a heads up; there seems to be a notorious bug with the GT new horizons instance with reikas mod chromaticraft bible crashed the game upon trying to place a block when looking at a ME cable

this has already been reported on their end and provided more in-depth. I'm just letting you know in case any reports of this comes up

**Comment by GlodBlock** [comment]
personally, i suggest to only play reika's mods with his own mods. gtnh itself contains a lot of breaking changes and it isn't meant to play with other mods.

**Comment by Shibva** [comment]
oh bud, im not that much of an idiot; ik for a fact that putting that in GNTH will break things, this was an out of pack thing with what I found on curse. Thanks for the concern and advice thou ^w^
