### ISSUE TITLE
in version v0.54.1, there is a crash with the ae2fc mod

### ISSUE THREAD

**Issue by Xikaro** [GlodBlock/AE2FluidCraft-Rework#54]
in version v0.54.1, there is a crash with the ae2fc mod

java.lang.ExceptionInInitializerError
    at com.glodblock.github.util.Ae2ReflectClient.<clinit>(Ae2ReflectClient.java:45)
    at com.glodblock.github.client.model.DenseEncodedPatternModel.bake(DenseEncodedPatternModel.java:42)
    at net.minecraftforge.client.model.ModelLoader.setupModelRegistry(ModelLoader.java:180)
    at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121)
    at net.minecraft.client.Minecraft.init(Minecraft.java:513)
    at net.minecraft.client.Minecraft.run(Minecraft.java:6101)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Failed to initialize AE2 reflection hacks!
    at com.glodblock.github.util.Ae2Reflect.<clinit>(Ae2Reflect.java:80)
    ... 14 more
Caused by: java.lang.NoSuchFieldException: Can't find field from [craftingSlots]
    at com.glodblock.github.util.Ae2Reflect.reflectField(Ae2Reflect.java:100)
    at com.glodblock.github.util.Ae2Reflect.<clinit>(Ae2Reflect.java:63)
    ... 14 more

- AE2 Version: v0.54.1
- Forge Version: 14.23.5.2860
- Minecraft 1.12.2
- Fluid Craft for AE2-2.4.1-r

**Comment by YiRanMushroom** [comment]
I think you should probably upgrade the version of AE2FC, I use the 2.4.2 version and it seems that it can run in the newest AE2(only with some subtle problems of ME interface).

**Comment by GlodBlock** [comment]
it is the recently update in pae2 causes the crash, i will fix it once trousers push the new version in cf

**Comment by GlodBlock** [comment]
btw ae2 v51 has refactor a lot of things, so after this fix ae2fc won't compatible with old pae2

**Comment by GlodBlock** [comment]
fixed in https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.3-r
waiting curseforge to approve
